"use strict";

// ── summary_writer.js — writes orchestration_summary.md for a completed loop.
//
// NOTE: This module does NOT call appendAuditRow(). The terminal-state
// transition is the final audit entry; the summary is a side-car markdown
// artifact only. "SUMMARY_WRITTEN" is not in VALID_TRANSITION_TYPES (contract
// §12.2 additionalProperties:false). See Stage 10.5 OQ4 resolution 2026-05-14.

const { getDefaultRegistry } = require("../tools/_registry");
const { getGraph }           = require("./loop_state");

function _reg() { return getDefaultRegistry(); }

function _logPath(project_id, loop_id) {
  return "artifacts/projects/" + project_id + "/orchestration/" + loop_id + "/conversation_log.jsonl";
}

function _summaryPath(project_id, loop_id) {
  return "artifacts/projects/" + project_id + "/orchestration/" + loop_id + "/orchestration_summary.md";
}

async function _readAuditRows(project_id, loop_id, ctx) {
  const result = await _reg().invoke(
    "fs.read_file",
    { path: _logPath(project_id, loop_id) },
    ctx || {}
  );
  if (result.status !== "SUCCESS" || !result.output || !result.output.content) {
    return [];
  }
  return result.output.content
    .trim()
    .split("\n")
    .filter(function(line) { return line.trim(); })
    .map(function(line) {
      try { return JSON.parse(line); } catch (_e) { return null; }
    })
    .filter(Boolean);
}

function _renderAuditTable(rows) {
  if (!rows.length) return "*No audit rows recorded.*\n";
  const header = "| # | From | To | Type | Timestamp |\n|---|---|---|---|---|\n";
  const body = rows.map(function(row, i) {
    return "| " + (i + 1) + " | " + (row.from_state || "?") +
           " | " + (row.to_state || "?") +
           " | " + (row.transition_type || "?") +
           " | " + (row.ts || "?") + " |";
  }).join("\n");
  return header + body + "\n";
}

// writeSummary(project_id, loop_id, ctx) → { path }
// Reads loop graph + audit log, writes orchestration_summary.md via registry.
// Track A: zero direct fs.*, zero new OpenAI(), zero fetch().

async function writeSummary(project_id, loop_id, ctx) {
  const ctxObj = ctx || {};

  const graph = await getGraph(project_id, loop_id, ctxObj);
  const rows  = await _readAuditRows(project_id, loop_id, ctxObj);

  const finalState  = graph ? graph.current_state    : "UNKNOWN";
  const iterations  = graph ? graph.iteration_count  : 0;
  const startedAt   = graph ? graph.started_at       : "unknown";
  const completedAt = graph ? graph.last_advanced_at : "unknown";

  const content = [
    "# Orchestration Loop Summary",
    "",
    "| Field | Value |",
    "|---|---|",
    "| Project | " + project_id + " |",
    "| Loop ID | " + loop_id + " |",
    "| Final state | " + finalState + " |",
    "| Iteration count | " + iterations + " |",
    "| Started | " + startedAt + " |",
    "| Completed | " + completedAt + " |",
    "| Audit rows | " + rows.length + " |",
    "",
    "## Audit Trail",
    "",
    _renderAuditTable(rows),
    "---",
    "*Generated by Forge orchestration summary_writer.js*"
  ].join("\n");

  const writeResult = await _reg().invoke(
    "fs.write_file",
    { path: _summaryPath(project_id, loop_id), content },
    ctxObj
  );
  if (writeResult.status !== "SUCCESS") {
    throw new Error(
      "writeSummary: fs.write_file failed: " +
      ((writeResult.metadata && writeResult.metadata.reason) || writeResult.status)
    );
  }

  return { path: _summaryPath(project_id, loop_id) };
}

module.exports = { writeSummary };
