"use strict";

// KB Layer constants — authoritative values per docs/12_ai_os/22_KNOWLEDGE_BASE_CONTRACT.md.
// @see docs/12_ai_os/22_KNOWLEDGE_BASE_CONTRACT.md §4 (chunking defaults) §9 (budget)

// ── Chunking ──────────────────────────────────────────────────────────────────

const CHUNK_SIZE_CHARS    = 1500;
const CHUNK_OVERLAP_CHARS = 200;

// semantic_v1 used for md/html; fixed_v1 for pdf/txt
const CHUNK_STRATEGY_BY_TYPE = {
  "text/markdown": "semantic_v1",
  "text/html":     "semantic_v1",
  "application/pdf": "fixed_v1",
  "text/plain":    "fixed_v1"
};

// ── Embedding ─────────────────────────────────────────────────────────────────

const EMBEDDING_MODEL      = "text-embedding-3-small";
const EMBEDDING_DIMENSIONS = 512;
const EMBEDDING_MODEL_ID   = "text-embedding-3-small@512";
const EMBEDDING_BATCH_SIZE = 100;

// ── Credibility ───────────────────────────────────────────────────────────────

const CREDIBILITY_FLOOR_DEFAULT = "REPUTABLE";

const CREDIBILITY_TIERS = {
  AUTHORITATIVE: { min: 0.80, max: 1.00 },
  REPUTABLE:     { min: 0.55, max: 0.79 },
  COMMUNITY:     { min: 0.30, max: 0.54 },
  LOW:           { min: 0.00, max: 0.29 }
};

// Domain patterns for heuristic scoring
const AUTHORITATIVE_DOMAIN_PATTERNS = [
  /^docs\.(python|nodejs|oracle|microsoft|apple)\.(?:org|com)$/i,
  /^developer\.(mozilla|apple)\.(?:org|com)$/i,
  /^(tools\.ietf|www\.rfc-editor|datatracker\.ietf)\.org$/i,
  /^(nodejs|reactjs|vuejs|angular|svelte)\.org$/i,
  /^(docs\.|learn\.|api\.)?(aws|azure|cloud\.google)\.com$/i,
  /^(docs|developer)\.(github|gitlab|docker)\.com$/i,
  /^(www\.)?(postgresql|mysql|mongodb|redis)\.org$/i,
  /^(www\.)?npmjs\.com$/i
];

const LOW_QUALITY_PATTERNS = [
  /\d{4,}[a-z]+\.(com|net|org)$/i,   // keyword-stuffed domains
  /^[a-z]{2,4}\d{3,}\./i,            // autogenerated-looking subdomains
  /^http:\/\//i                       // no HTTPS (applied to URL string, not domain)
];

// ── Budget ────────────────────────────────────────────────────────────────────

const BUDGET_DEFAULT_USD      = 1.50;
const BUDGET_HARD_CEILING_USD = 5.00;
const BUDGET_WARN_THRESHOLD   = 0.70;  // 70% → WARN_70PCT

// ── Storage paths ─────────────────────────────────────────────────────────────

const KB_BASE_REL         = "artifacts/projects";
const KB_GLOBAL_BASE_REL  = "artifacts/_global_kb";
const COST_LEDGER_REL     = "kb/cost_ledger.jsonl";
const EXPORTS_REL         = "kb/exports";

// ── Search ────────────────────────────────────────────────────────────────────

const MAX_SEARCHES_DEFAULT = 10;
const RETRIEVAL_K_DEFAULT  = 5;

// Brave Search API base URL (routed through L2 http tool)
const BRAVE_SEARCH_API_BASE = "https://api.search.brave.com/res/v1/web/search";
const TAVILY_API_BASE       = "https://api.tavily.com/search";

// Allowed content-types for web fetch
const ALLOWED_FETCH_CONTENT_TYPES = [
  "text/html",
  "text/markdown",
  "text/plain",
  "application/pdf"
];

module.exports = {
  CHUNK_SIZE_CHARS,
  CHUNK_OVERLAP_CHARS,
  CHUNK_STRATEGY_BY_TYPE,
  EMBEDDING_MODEL,
  EMBEDDING_DIMENSIONS,
  EMBEDDING_MODEL_ID,
  EMBEDDING_BATCH_SIZE,
  CREDIBILITY_FLOOR_DEFAULT,
  CREDIBILITY_TIERS,
  AUTHORITATIVE_DOMAIN_PATTERNS,
  LOW_QUALITY_PATTERNS,
  BUDGET_DEFAULT_USD,
  BUDGET_HARD_CEILING_USD,
  BUDGET_WARN_THRESHOLD,
  KB_BASE_REL,
  KB_GLOBAL_BASE_REL,
  COST_LEDGER_REL,
  EXPORTS_REL,
  MAX_SEARCHES_DEFAULT,
  RETRIEVAL_K_DEFAULT,
  BRAVE_SEARCH_API_BASE,
  TAVILY_API_BASE,
  ALLOWED_FETCH_CONTENT_TYPES
};
